apiVersion: v1
kind: Pod
metadata:
  name: task1
  labels:
    app: task1-app
spec:
  containers:
  - image: thulasiprasad2000/task1jenk
    name: task1
    env:
    - name: YOUR_NAME
      valueFrom:
        secretKeyRef:
          name: your-name
          key: yourname
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: task1-app
spec:
  type: ClusterIP
  selector:
    app: task1-app
  ports:
    - port: 5500
      protocol: TCP